version: '3.8'

volumes:
  pgdata:  # Define the pgdata volume

networks:
  ffmpeg_network:
    driver: bridge
    # ipam:
    #   driver: default
    #   config:
    #     - subnet: 172.20.0.0/16
services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data  # Define the volume pgdata
    ports:
      - "5432:5432"
    #network_mode: host  # Attach the container to the host network


  ffmpeg0:
    image: dasher
    container_name: dasher1
    #command: ["./myapp"]
    volumes:
      - ./Multicast/source1.mp4:/input/source1.mp4:ro
    ports:
      - "4000:4000"
    networks:
      - ffmpeg_network


  ffmpeg1:
    image: opencoconut/ffmpeg:latest
    container_name: source1
    command: ["-re", "-stream_loop", "-1", "-i", "/input/source1.mp4", "-vcodec", "copy", "-acodec", "copy", "-f", "mpegts", "udp://235.235.235.235:1111?pkt_size=1316"]
    volumes:
      - ./Multicast/source1.mp4:/input/source1.mp4:ro
    networks:
      - ffmpeg_network

  ffmpeg2:
    image: opencoconut/ffmpeg:latest
    container_name: source2
    command: ["-re", "-stream_loop", "-1", "-i", "/input/source2.mp4", "-vcodec", "copy", "-acodec", "copy", "-f", "mpegts", "udp://235.235.235.235:2222?pkt_size=1316"]
    volumes:
      - ./Multicast/source2.mp4:/input/source2.mp4:ro
    networks:
      - ffmpeg_network

  ffmpeg3:
    image: opencoconut/ffmpeg:latest
    container_name: source3
    command: ["-re", "-stream_loop", "-1", "-i", "/input/source3.mp4", "-vcodec", "copy", "-acodec", "copy", "-f", "mpegts", "udp://235.235.235.235:3333?pkt_size=1316"]
    volumes:
      - ./Multicast/source3.mp4:/input/source3.mp4:ro
    networks:
      - ffmpeg_network


  ffmpeg4:
    image: opencoconut/ffmpeg:latest
    container_name: source4
    command: ["-re", "-stream_loop", "-1", "-i", "/input/source4.mp4", "-vcodec", "copy", "-acodec", "copy", "-f", "mpegts", "udp://235.235.235.235:4444?pkt_size=1316"]
    volumes:
      - ./Multicast/source4.mp4:/input/source4.mp4:ro
    networks:
      - ffmpeg_network


  ffmpeg5:
    image: opencoconut/ffmpeg:latest
    container_name: source5
    command: ["-re", "-stream_loop", "-1", "-i", "/input/source5.mp4", "-vcodec", "copy", "-acodec", "copy", "-f", "mpegts", "udp://235.235.235.235:5555?pkt_size=1316"]
    volumes:
      - ./Multicast/source5.mp4:/input/source5.mp4:ro
    networks:
      - ffmpeg_network
