version: '3.9'

volumes:
  pgdata:  # Define the pgdata volume

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.254

services:
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data  # Define the volume pgdata
    ports:
      - "5432:5432"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.100
    #network_mode: host  # Attach the container to the host network


  ffmpeg0:
    image: dasher
    container_name: dasher1
    #command: ["./myapp"]
    ports:
      - "4000:4000"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.99


  # ffmpeg1:
  #   image: opencoconut/ffmpeg:latest
  #   container_name: source1
  #   command: ["-re", "-stream_loop", "-1", "-i", "/input/source1.mp4", "-vcodec", "copy", "-acodec", "copy", "-f", "mpegts", "udp://235.235.235.235:11111?pkt_size=1316"]
  #   volumes:
  #     - ./Multicast/source1.mp4:/input/source1.mp4:ro
  #   networks:
  #     vpcbr:
  #       ipv4_address: 10.5.0.1

  ffmpeg2:
    image: opencoconut/ffmpeg:latest
    container_name: source2
    command: ["-re", "-stream_loop", "-1", "-i", "/input/source2.mp4", "-vcodec", "copy", "-acodec", "copy", "-f", "mpegts", "udp://235.235.235.235:22222?pkt_size=1316"]
    volumes:
      - ./Multicast/source2.mp4:/input/source2.mp4:ro
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  ffmpeg3:
    image: opencoconut/ffmpeg:latest
    container_name: source3
    command: ["-re", "-stream_loop", "-1", "-i", "/input/source3.mp4", "-vcodec", "copy", "-acodec", "copy", "-f", "mpegts", "udp://235.235.235.235:33333?pkt_size=1316"]
    volumes:
      - ./Multicast/source3.mp4:/input/source3.mp4:ro
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3


  # ffmpeg4:
  #    image: opencoconut/ffmpeg:latest
  #    container_name: source4
  #    command: ["-re", "-stream_loop", "-1", "-i", "/input/source4.mp4", "-vcodec", "copy", "-acodec", "copy", "-f", "mpegts", "udp://235.235.235.235:44444?pkt_size=1316"]
  #    volumes:
  #      - ./Multicast/source5.mp4:/input/source4.mp4:ro
  #    networks:
  #      vpcbr:
  #        ipv4_address: 10.5.0.4


  # ffmpeg5:
  #    image: opencoconut/ffmpeg:latest
  #    container_name: source5
  #    command: ["-re", "-stream_loop", "-1", "-i", "/input/source5.mp4", "-vcodec", "copy", "-acodec", "copy", "-f", "mpegts", "udp://235.235.235.235:55555?pkt_size=1316"]
  #    volumes:
  #      - ./Multicast/source4.mp4:/input/source5.mp4:ro
  #    networks:
  #      vpcbr:
  #        ipv4_address: 10.5.0.5
